"use strict";

/* =========================================================
   Settings
   ========================================================= */

// Your contact link (Facebook profile, Messenger, Telegram, or an email as
// "mailto:you@example.com"). While this is empty, every "Contact me" link on
// the site stays hidden. Set this before launch: a working way to request a
// correction is part of running a list like this responsibly.
const CONTACT_URL = "";

// Minimum time between checks, in milliseconds. This only slows down casual
// clicking. It runs in the visitor's browser, so it is not real protection.
const CHECK_COOLDOWN_MS = 3000;

/* =========================================================
   Tabs
   ========================================================= */

const tabs = Array.from(document.querySelectorAll('[role="tab"]'));
const panels = Array.from(document.querySelectorAll('[role="tabpanel"]'));

function activateTab(tab, { focus = false, updateHash = true } = {}) {
  const panelId = tab.getAttribute("aria-controls");

  tabs.forEach((t) => {
    const selected = t === tab;
    t.setAttribute("aria-selected", String(selected));
    t.tabIndex = selected ? 0 : -1;
  });
  panels.forEach((p) => {
    p.hidden = p.id !== panelId;
  });

  if (focus) tab.focus();

  if (updateHash) {
    try {
      history.replaceState(null, "", "#" + panelId);
    } catch (err) {
      /* history can be blocked (e.g. file://). The tab still works. */
    }
  }
  window.scrollTo(0, 0);
}

function tabFromHash() {
  const id = location.hash.slice(1);
  return tabs.find((t) => t.getAttribute("aria-controls") === id);
}

function selectedIndex() {
  return tabs.findIndex((t) => t.getAttribute("aria-selected") === "true");
}

tabs.forEach((tab) => {
  tab.addEventListener("click", () => activateTab(tab));
});

// Arrow keys, Home and End move between tabs
document.querySelector('[role="tablist"]').addEventListener("keydown", (e) => {
  const last = tabs.length - 1;
  let next = null;
  if (e.key === "ArrowRight") next = (selectedIndex() + 1) % tabs.length;
  else if (e.key === "ArrowLeft")
    next = (selectedIndex() - 1 + tabs.length) % tabs.length;
  else if (e.key === "Home") next = 0;
  else if (e.key === "End") next = last;
  if (next === null) return;
  e.preventDefault();
  activateTab(tabs[next], { focus: true });
});

// Open the tab named in the URL (e.g. .../#check), and follow back/forward
const startTab = tabFromHash();
if (startTab) activateTab(startTab, { updateHash: false });

window.addEventListener("hashchange", () => {
  const tab = tabFromHash();
  if (tab) activateTab(tab, { updateHash: false });
});

/* =========================================================
   Swipe between tabs (touch screens)
   ========================================================= */

let touchStart = null;

document.addEventListener(
  "touchstart",
  (e) => {
    // Ignore multi-touch, and swipes that start in the input box
    if (e.touches.length !== 1 || e.target.closest("input")) {
      touchStart = null;
      return;
    }
    touchStart = { x: e.touches[0].clientX, y: e.touches[0].clientY };
  },
  { passive: true },
);

document.addEventListener(
  "touchend",
  (e) => {
    if (!touchStart) return;
    const touch = e.changedTouches[0];
    const dx = touch.clientX - touchStart.x;
    const dy = touch.clientY - touchStart.y;
    touchStart = null;

    const MIN_DISTANCE = 60;
    const isMostlyHorizontal = Math.abs(dx) >= Math.abs(dy) * 2;
    if (Math.abs(dx) < MIN_DISTANCE || !isMostlyHorizontal) return;
    if (String(window.getSelection())) return; // user is selecting text

    const next = tabs[selectedIndex() + (dx < 0 ? 1 : -1)];
    if (next) activateTab(next);
  },
  { passive: true },
);

/* =========================================================
   Contact links
   ========================================================= */

if (CONTACT_URL) {
  document.querySelectorAll("a[data-contact]").forEach((a) => {
    a.href = CONTACT_URL;
  });
  document.querySelectorAll("[data-contact-wrap]").forEach((el) => {
    el.hidden = false;
  });
}

/* =========================================================
   Number check
   SALT, ITERATIONS and REPORTS come from data.js (generated by
   tools/build-data.js). No phone number is ever stored in this site.
   ========================================================= */

// <lookup-core>

// Turns "+63 994-731-4166", "63994...", "9947314166" and "0994 731 4166"
// into the local format "09947314166". Keep identical to build-data.js.
function toLocalNumber(input) {
  let digits = String(input).replace(/\D/g, "");
  if (digits.startsWith("63") && digits.length === 12)
    digits = "0" + digits.slice(2);
  else if (digits.startsWith("9") && digits.length === 10)
    digits = "0" + digits;
  return digits;
}

function isValidNumber(number) {
  return /^09\d{9}$/.test(number);
}

// Salted PBKDF2-SHA256, returned as hex. Must match build-data.js.
async function hashNumber(number, salt, iterations) {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    enc.encode(number),
    "PBKDF2",
    false,
    ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    {
      name: "PBKDF2",
      hash: "SHA-256",
      salt: enc.encode(salt),
      iterations: iterations,
    },
    key,
    256,
  );
  return Array.from(new Uint8Array(bits), (b) =>
    b.toString(16).padStart(2, "0"),
  ).join("");
}

async function findReport(number, reports, salt, iterations) {
  const hash = await hashNumber(number, salt, iterations);
  return reports.find((r) => r.hash === hash) || null;
}

// </lookup-core>

const form = document.getElementById("check-form");
const numberInput = document.getElementById("number");
const checkBtn = document.getElementById("check-btn");
const statusEl = document.getElementById("check-status");
const resultEl = document.getElementById("result");

let lastCheck = 0;

// Builds the result card. Only textContent is used, so data can never
// inject HTML into the page.
function showResult(paragraphs, { withContact = false } = {}) {
  resultEl.replaceChildren();
  paragraphs.forEach((text) => {
    const p = document.createElement("p");
    p.style = "text-align: center";
    p.textContent = text;
    resultEl.append(p);
  });
  if (withContact && CONTACT_URL) {
    const p = document.createElement("p");
    const a = document.createElement("a");
    a.href = CONTACT_URL;
    a.target = "_blank";
    a.rel = "noopener noreferrer";
    a.textContent = "Request a correction or removal";
    p.append(a);
    resultEl.append(p);
  }
  resultEl.hidden = false;
}

function setBusy(busy) {
  checkBtn.disabled = busy;
  checkBtn.textContent = busy ? "Checking…" : "Check number";
}

form.addEventListener("submit", async (e) => {
  e.preventDefault();
  resultEl.hidden = true;
  statusEl.textContent = "";

  if (typeof REPORTS === "undefined" || typeof SALT === "undefined") {
    statusEl.textContent =
      "The data file did not load. Refresh the page and try again.";
    return;
  }
  if (!window.crypto || !window.crypto.subtle) {
    statusEl.textContent =
      "This browser can't run the check. Open the site over https in an up-to-date browser.";
    return;
  }

  const number = toLocalNumber(numberInput.value);
  if (!isValidNumber(number)) {
    statusEl.textContent =
      "Enter the full 11-digit mobile number, like 0917 123 4567 or +63 917 123 4567.";
    numberInput.focus();
    return;
  }

  const wait = CHECK_COOLDOWN_MS - (Date.now() - lastCheck);
  if (wait > 0) {
    statusEl.textContent = `Please wait ${Math.ceil(wait / 1000)} seconds before checking again.`;
    return;
  }
  lastCheck = Date.now();

  setBusy(true);
  try {
    const hit = await findReport(number, REPORTS, SALT, ITERATIONS);
    if (hit) {
      showResult(
        [
          "✅✅ Record found! ✅✅",
          `I paid ${hit.amount} on ${hit.date} for ${hit.item} and had not received it as of ${hit.updated}.`,
          "This is one buyer's experience, feel free to message me if you need the proofs. If it is inaccurate, or the number has changed hands, please tell me and I will correct or remove it.",
        ],
        { withContact: true },
      );
    } else {
      showResult([
        "❌❌ No record found for this number. ❌❌",
        "Stay safe and good luck purchasing!",
      ]);
    }
  } catch (err) {
    statusEl.textContent = "Something went wrong while checking. Try again.";
  } finally {
    setBusy(false);
  }
});
